### ISSUE TITLE
Game broken

### ISSUE THREAD

**Issue by githubteacher** [githubschool/github-games-PixnBits#1]
When attempting to access this at https://githubschool.github.io/github-games-PixnBits/, I am getting a 404. This could be caused by a couple things:

 - GitHub pages needs to be enabled on master. You can fix this in the repository settings.
- the index.html file is incorrectly named inde.html. We will fix this together in class.

 Can you please fix the first bullet @PixnBits?

**Comment by PixnBits** [comment]
fixed by 3f1b5ba1c266b5b4b3fa765613ec022019631207
